name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install uv
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Run black check
      run: |
        source .venv/bin/activate
        black --check src/ tests/

    - name: Run isort check
      run: |
        source .venv/bin/activate
        isort --check-only src/ tests/

    - name: Run flake8 linter
      run: |
        source .venv/bin/activate
        flake8 src/ tests/

    - name: Run mypy type checker
      run: |
        source .venv/bin/activate
        mypy src/

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/
